name: Spring Docker Image CI

on:
  push:
    branches: ["deploy"]

env:
  MYSQL_URL: ${{ secrets.MYSQL_URL }}
  MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
  MYSQL_PW: ${{ secrets.MYSQL_PW }}
  JWT_SECURITY_KEY: ${{ secrets.JWT_SECURITY_KEY }}
  REDIS_URL: ${{ secrets.REDIS_URL }}
  REDIS_PW: ${{ secrets.REDIS_PW }}
  FLASK_URL: ${{ secrets.FLASK_URL }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: deploy
      
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Grant Execute Permission for gradlew  
      run: chmod +x springboot/curry/gradlew

    - name: Replace secrets in application.properites
      working-directory: springboot/curry/src/main/resources
      run: |
        sed -i "s|{MYSQL_URL}|${MYSQL_URL}|g" application-local.properties
        sed -i "s|{MYSQL_USERNAME}|${MYSQL_USERNAME}|g" application-local.properties
        sed -i "s|{MYSQL_PW}|${MYSQL_PW}|g" application-local.properties
        sed -i "s|{JWT_SECURITY_KEY}|${JWT_SECURITY_KEY}|g" application-local.properties
        sed -i "s|{REDIS_URL}|${REDIS_URL}|g" application-local.properties
        sed -i "s|{REDIS_PW}|${REDIS_PW}|g" application-local.properties
        sed -i "s|{FLASK_URL}|${FLASK_URL}|g" application-local.properties

    - name: SpringBoot Build
      working-directory: springboot/curry
      run: ./gradlew clean build --exclude-task test
    
    - name: SpringBoot Docker Image Build
      working-directory: springboot/curry
      run: docker build . --file Dockerfile --tag kimgagyeong/curry:springboot

    - name: Docker Login
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker Hub Push
      run: docker push kimgagyeong/curry:springboot
