name: Spring Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Change Working Directory to Project Root
      run: cd springboot/curry

    - name: Grant Execute Permission for gradlew  
      run: chmod +x gradlew
      
    - name: SpringBoot Build
      run: ./gradlew clean build --exclude-task test
    
    - name: SpringBoot Docker Image Build
      run: docker build . --file Dockerfile --tag kimgagyeong/curry:springboot

    - name: Docker Login
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker Hub Push
      run: docker push kimgagyeong/curry:springboot
